version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html  # Монтируем папку app как корень
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: .
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_DATABASE=codeigniter
      - DB_USERNAME=ci_user
      - DB_PASSWORD=ci_password

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=codeigniter
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge